train_file: '/nfs4-p1/ljt/Code/ptu/dataset_coin/coin_train_text.json'
test_file: '/nfs4-p1/ljt/Code/ptu/dataset_coin/coin_test_text.json'
batch_size_train: 4
batch_size_test: 4

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-5, epochs: 30, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}